[2023-04-30T21:40:35.205+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: basic_etl_dag.transform_task manual__2023-04-30T21:40:26.293455+00:00 [queued]>
[2023-04-30T21:40:35.211+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: basic_etl_dag.transform_task manual__2023-04-30T21:40:26.293455+00:00 [queued]>
[2023-04-30T21:40:35.211+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T21:40:35.211+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-04-30T21:40:35.212+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-30T21:40:35.248+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): transform_task> on 2023-04-30 21:40:26.293455+00:00
[2023-04-30T21:40:35.252+0000] {standard_task_runner.py:55} INFO - Started process 30607 to run task
[2023-04-30T21:40:35.256+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'basic_etl_dag', 'transform_task', 'manual__2023-04-30T21:40:26.293455+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmprt4tesg7']
[2023-04-30T21:40:35.258+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask transform_task
[2023-04-30T21:40:35.323+0000] {task_command.py:388} INFO - Running <TaskInstance: basic_etl_dag.transform_task manual__2023-04-30T21:40:26.293455+00:00 [running]> on host codespaces-f747d3
[2023-04-30T21:40:35.543+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=basic_etl_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T21:40:26.293455+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T21:40:26.293455+00:00
[2023-04-30T21:40:35.550+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/workspaces/airflow_etl/airflow/dags/etl_dag.py", line 27, in transform_data
    generic_type_df.to_csv('/workspaces/airflow_etl/data/transform_sp500.csv', index=False)
NameError: name 'generic_type_df' is not defined
[2023-04-30T21:40:35.560+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=basic_etl_dag, task_id=transform_task, execution_date=20230430T214026, start_date=20230430T214035, end_date=20230430T214035
[2023-04-30T21:40:35.599+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 7 for task transform_task (name 'generic_type_df' is not defined; 30607)
[2023-04-30T21:40:35.628+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-30T21:40:35.648+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
